{% set name = "opentelemetry-instrumentation-ollama" %}
{% set version = "0.62.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 0db8b4522ffbf3ee8e0c41e0cf1197b09d8a42a0346dcc11f6eaed8f3e336cba

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0
    - opentelemetry-semantic-conventions >=0.63b1

# Unable to run tests and check imports, ollama is not in the main channel.
test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Ollama instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing calls to any of Ollama's endpoints sent with the official Ollama Python Library.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - reachable_url
    - missing_imports_or_run_test_py
